import { LANGUAGE_COMMAND } from './language/index.js';
import { SUMMARIZE_COMMAND } from './summarize/index.js';
import {
    TRANSLATE_CHAT_CONTEXT_MENU,
    TRANSLATE_CHAT_MODAL,
    TRANSLATE_COMMAND,
    TRANSLATE_MESSAGE_CONTEXT_MENU,
    TRANSLATE_MESSAGE_MODAL,
} from './translate/index.js';

export const COMMANDS = [
    LANGUAGE_COMMAND,
    SUMMARIZE_COMMAND,
    TRANSLATE_COMMAND,
    TRANSLATE_CHAT_CONTEXT_MENU,
    TRANSLATE_MESSAGE_CONTEXT_MENU,
];

export const MODALS = [TRANSLATE_CHAT_MODAL, TRANSLATE_MESSAGE_MODAL];
